db:
  filePath: data

block:
  genesisBlockPath: genesis.json
  isSync: true
  version: 1
  target: 1

neo4j:
  path: neo4j

tayi:
  vm:
    path: vm
    ipfs:
      host: /ip4/127.0.0.1/tcp/5001
    contract:
      path: contracts
  network:
    init:
      ip: 127.0.0.1
      port: 9998
    socket:
      port: 9999

spring:
  rsocket:
    server:
      port: 7545
      transport: tcp

server:
  port: 8081


dubbo:
  application:
    name: dubbo-demo
  registry:
    address=N/A  # 指定不使用注册中心

